Add additional checkings.

diff --git a/reconf b/reconf
--- a/reconf
+++ b/reconf
@@ -1,16 +1,37 @@
-echo "Perform checkings before reconfiguring package..."
+echo "* Perform checkings before reconfiguring package..."
+
+# Check autotools
+echo -n "- Checking that autotools are present..."
+err=0
+autoconf --version >/dev/null 2>&1 || err=1
+automake --version >/dev/null 2>&1 || err=1
+libtool --version >/dev/null 2>&1 || err=1
+
+if [ $err -eq 1 ]; then
+   echo ""
+   echo "**Error**: autotools not available."
+   echo ""
+   echo "Make sure that the autotools are installed."
+   exit 1
+else
+   echo " OK"
+fi
 
 # Check libtoolize
+echo -n "- Checking libtoolize..."
 err=`libtoolize -n --quiet 2>&1 | grep "not found" | wc -l`
 
 if [ $err -eq 1 ]; then
+   echo ""
    echo "**Error**: libtoolize cannot detect necessary files."
    echo ""
    echo "Make sure libtool-ltdl-devel (rpm) / libltdl-dev (deb) or an"
    echo "appropriate package for your distribution is installed."
    exit 1
+else
+   echo " OK"
 fi
 
 # Reconfigure package
-echo "Reconfigure package..."
+echo "* Reconfigure package..."
 autoreconf -i -I m4 --force
